### ISSUE TITLE
[Issue]  Mismatch in tensor dimensions between 'input_ids' and 'output_ids' at the specified dimension.

### ISSUE THREAD

**Issue by tarekdawey** [WisconsinAIVision/ViP-LLaVA#18]
### Describe the issue

Hi ,
Thanks for your great work. I am trying to run the quick start as specified in the repository but facing this issue:

Traceback (most recent call last):
  File "/media/local/tdawey/ViP-LLaVA/quick_start.py", line 17, in <module>
    eval_model(args)
  File "/media/local/tdawey/ViP-LLaVA/llava/eval/run_llava.py", line 128, in eval_model
    n_diff_input_output = (input_ids != output_ids[:, :input_token_len]).sum().item()
RuntimeError: The size of tensor a (53) must match the size of tensor b (16) at non-singleton dimension 1

Could you please look into this and explain why this is happening and help me resolve it?

**Comment by mu-cai** [comment]
Hi taredawey, this is due to the transformers version mismatch. 


I have updated run_llava.py, can you pull and test again?

**Comment by tarekdawey** [comment]
Thanks a lot for your prompt response! It works now. I really appreciate you help.
