### ISSUE TITLE
[Usage] can't do the gradio demo install error

### ISSUE THREAD

**Issue by JustinKai0527** [WisconsinAIVision/ViP-LLaVA#24]
### Describe the issue

![image](https://github.com/user-attachments/assets/dcc48d5f-d939-48bd-a19e-b5bb094036ec)
after install I run the in the terminal occur this problem and I fix by downgrade the gradio but got another error....
![image](https://github.com/user-attachments/assets/c6efa4b2-e34e-4012-a44d-ed7b2e418e50)

`(vip-llava) kai@user:~/project/ViP-LLaVA$ python -m llava.serve.model_worker --host 0.0.0.0 --controller http://localhost:10000 --port 40000 --worker http://localhost:40000 --model-path ../model_weight/
`flash-attention` package not found, consider installing for better performance: No module named 'flash_attn'.
Current `flash-attenton` does not support `window_size`. Either upgrade or use `attn_implementation='eager'`.
2024-07-29 15:42:08 | INFO | model_worker | args: Namespace(host='0.0.0.0', port=40000, worker_address='http://localhost:40000', controller_address='http://localhost:10000', model_path='../model_weight/', model_base=None, model_name=None, device='cuda', multi_modal=False, limit_model_concurrency=5, stream_interval=1, no_register=False, load_8bit=False, load_4bit=False)
2024-07-29 15:42:08 | INFO | model_worker | Loading the model model_weight on worker 43c283 ...
2024-07-29 15:42:08 | ERROR | stderr | Traceback (most recent call last):
2024-07-29 15:42:08 | ERROR | stderr |   File "/home/kai/miniconda3/envs/vip-llava/lib/python3.10/runpy.py", line 196, in _run_module_as_main
2024-07-29 15:42:08 | ERROR | stderr |     return _run_code(code, main_globals, None,
2024-07-29 15:42:08 | ERROR | stderr |   File "/home/kai/miniconda3/envs/vip-llava/lib/python3.10/runpy.py", line 86, in _run_code
2024-07-29 15:42:08 | ERROR | stderr |     exec(code, run_globals)
2024-07-29 15:42:08 | ERROR | stderr |   File "/home/kai/project/ViP-LLaVA/llava/serve/model_worker.py", line 275, in <module>
2024-07-29 15:42:08 | ERROR | stderr |     worker = ModelWorker(args.controller_address,
2024-07-29 15:42:08 | ERROR | stderr |   File "/home/kai/project/ViP-LLaVA/llava/serve/model_worker.py", line 65, in __init__
2024-07-29 15:42:08 | ERROR | stderr |     self.tokenizer, self.model, self.image_processor, self.context_len = load_pretrained_model(
2024-07-29 15:42:08 | ERROR | stderr |   File "/home/kai/project/ViP-LLaVA/llava/model/builder.py", line 129, in load_pretrained_model
2024-07-29 15:42:08 | ERROR | stderr |     tokenizer = AutoTokenizer.from_pretrained(model_path, use_fast=False)
2024-07-29 15:42:08 | ERROR | stderr |   File "/home/kai/miniconda3/envs/vip-llava/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 814, in from_pretrained
2024-07-29 15:42:08 | ERROR | stderr |     return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
2024-07-29 15:42:08 | ERROR | stderr |   File "/home/kai/miniconda3/envs/vip-llava/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2029, in from_pretrained
2024-07-29 15:42:08 | ERROR | stderr |     return cls._from_pretrained(
2024-07-29 15:42:08 | ERROR | stderr |   File "/home/kai/miniconda3/envs/vip-llava/lib/python3.10/site-packages/transformers/tokenization_utils_base.py", line 2261, in _from_pretrained
2024-07-29 15:42:08 | ERROR | stderr |     tokenizer = cls(*init_inputs, **init_kwargs)
2024-07-29 15:42:08 | ERROR | stderr |   File "/home/kai/miniconda3/envs/vip-llava/lib/python3.10/site-packages/transformers/models/llama/tokenization_llama.py", line 178, in __init__
2024-07-29 15:42:08 | ERROR | stderr |     self.sp_model = self.get_spm_processor(kwargs.pop("from_slow", False))
2024-07-29 15:42:08 | ERROR | stderr |   File "/home/kai/miniconda3/envs/vip-llava/lib/python3.10/site-packages/transformers/models/llama/tokenization_llama.py", line 208, in get_spm_processor
2024-07-29 15:42:08 | ERROR | stderr |     model_pb2 = import_protobuf(f"The new behaviour of {self.__class__.__name__} (with `self.legacy = False`)")
2024-07-29 15:42:08 | ERROR | stderr |   File "/home/kai/miniconda3/envs/vip-llava/lib/python3.10/site-packages/transformers/convert_slow_tokenizer.py", line 43, in import_protobuf
2024-07-29 15:42:08 | ERROR | stderr |     raise ImportError(PROTOBUF_IMPORT_ERROR.format(error_message))
2024-07-29 15:42:08 | ERROR | stderr | ImportError:
2024-07-29 15:42:08 | ERROR | stderr | The new behaviour of LlamaTokenizer (with `self.legacy = False`) requires the protobuf library but it was not found in your environment. Checkout the instructions on the
2024-07-29 15:42:08 | ERROR | stderr | installation page of its repo: https://github.com/protocolbuffers/protobuf/tree/master/python#installation and follow the ones
2024-07-29 15:42:08 | ERROR | stderr | that match your environment. Please note that you may need to restart your runtime after installation.
2024-07-29 15:42:08 | ERROR | stderr | `

**Comment by JustinKai0527** [comment]
is that the gradio version problem?

**Comment by JustinKai0527** [comment]
![image](https://github.com/user-attachments/assets/d387789c-f616-4465-8f7d-27bc7aad460d)
also got this problem 
I tried using pip install --force-reinstall -v "transformers==4.31.0" but didn't work
can you give me your pip list so I can check the different?

**Comment by mu-cai** [comment]
Here is my pip list. Thanks!
```
Package                   Version      Editable project location
------------------------- ------------ -------------------------------------------
accelerate                0.21.0
aiofiles                  23.2.1
aiohttp                   3.9.1
aiosignal                 1.3.1
altair                    5.2.0
annotated-types           0.6.0
anyio                     3.7.1
async-timeout             4.0.3
attrs                     23.1.0
bitsandbytes              0.41.0
certifi                   2023.11.17
charset-normalizer        3.3.2
click                     8.1.7
cmake                     3.27.9
colorama                  0.4.6
contourpy                 1.2.0
cycler                    0.12.1
deepspeed                 0.14.0
einops                    0.6.1
einops-exts               0.0.4
exceptiongroup            1.2.0
fastapi                   0.104.1
ffmpy                     0.3.1
filelock                  3.13.1
fonttools                 4.46.0
frozenlist                1.4.0
fsspec                    2023.12.0
gradio                    4.9.1
gradio_client             0.7.3
h11                       0.14.0
hjson                     3.1.0
httpcore                  0.17.3
httpx                     0.24.0
huggingface-hub           0.19.4
idna                      3.6
importlib-resources       6.1.1
Jinja2                    3.1.2
joblib                    1.3.2
jsonschema                4.20.0
jsonschema-specifications 2023.11.2
kiwisolver                1.4.5
linkify-it-py             2.0.2
lit                       17.0.6
markdown-it-py            2.2.0
markdown2                 2.4.11
MarkupSafe                2.1.3
matplotlib                3.8.2
mdit-py-plugins           0.3.3
mdurl                     0.1.2
mpmath                    1.3.0
multidict                 6.0.4
networkx                  3.2.1
ninja                     1.11.1.1
numpy                     1.26.2
nvidia-cublas-cu11        11.10.3.66
nvidia-cuda-cupti-cu11    11.7.101
nvidia-cuda-nvrtc-cu11    11.7.99
nvidia-cuda-runtime-cu11  11.7.99
nvidia-cudnn-cu11         8.5.0.96
nvidia-cufft-cu11         10.9.0.58
nvidia-curand-cu11        10.2.10.91
nvidia-cusolver-cu11      11.4.0.1
nvidia-cusparse-cu11      11.7.4.91
nvidia-nccl-cu11          2.14.3
nvidia-nvtx-cu11          11.7.91
openai                    0.28.0
opencv-python             4.9.0.80
orjson                    3.9.10
packaging                 23.2
pandas                    2.1.3
peft                      0.4.0
Pillow                    10.1.0
pip                       23.3.1
psutil                    5.9.6
py-cpuinfo                9.0.0
pydantic                  2.5.2
pydantic_core             2.14.5
pydub                     0.25.1
Pygments                  2.17.2
pynvml                    11.5.0
pyparsing                 3.1.1
python-dateutil           2.8.2
python-multipart          0.0.6
pytz                      2023.3.post1
PyYAML                    6.0.1
referencing               0.31.1
regex                     2023.10.3
requests                  2.31.0
rich                      13.7.0
rpds-py                   0.13.2
safetensors               0.4.1
scikit-learn              1.2.2
scipy                     1.11.4
semantic-version          2.10.0
sentencepiece             0.1.99
setuptools                68.0.0
shapely                   2.0.4
shellingham               1.5.4
shortuuid                 1.0.11
six                       1.16.0
sniffio                   1.3.0
starlette                 0.27.0
svgwrite                  1.4.3
sympy                     1.12
threadpoolctl             3.2.0
timm                      0.6.13
tokenizers                0.13.3
tomlkit                   0.12.0
toolz                     0.12.0
torch                     2.0.1
torchvision               0.15.2
tqdm                      4.66.1
transformers              4.31.0
triton                    2.0.0
typer                     0.9.0
typing_extensions         4.8.0
tzdata                    2023.3
uc-micro-py               1.0.2
urllib3                   2.1.0
uvicorn                   0.24.0.post1
vip-llava                 1.1.3       /home/mucai/code/ViP-LLaVA
wavedrom                  2.0.3.post3
websockets                11.0.3
wheel                     0.41.2
yarl                      1.9.3
```

**Comment by JustinKai0527** [comment]
@mu-cai thanks for replying, here is my pip list I run your install guideline 
I face the error 
```from .model import LlavaLlamaForCausalLM, LlavaPhi3ForCausalLM
ImportError: cannot import name 'LlavaLlamaForCausalLM' from 'llava.model'
``` 
which is seem the new version transformers can't import so I downgrade to transformers==4.31.0 same as you but got the error `ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
vip-llava 1.2.2.post1 requires tokenizers==0.15.1, but you have tokenizers 0.13.3 which is incompatible.
vip-llava 1.2.2.post1 requires transformers==4.37.2, but you have transformers 4.31.0 which is incompatible.`
so vip-llava 1.2.2 can't compatible, and your vip-llava is 1.1.3 which I don't know how to downgrade, how to solve ......
[requirements.txt](https://github.com/user-attachments/files/16420729/requirements.txt)
